### ISSUE TITLE
Staking is broken for any denominator > 1

### ISSUE THREAD

**Issue by dshaw002** [gemworks/gem-farm#12]
Every time you refresh a farmer's state, the new start time is the updated_time. This is fine if you're using rewards per second, but if you're using any larger interval, you will start from scratch. Additionally, any user can refresh farmer state, so someone could perpetually refresh farmer state and prevent them from accruing rewards.

In this example, I set the reward to 1 token per minute. I should have 3 tokens by the given time interval, but I only have 1. This is because I refreshed the state before a minute was up. Only once did a let a whole minute pass.

I made a kinda hack update that rounds the updated_ts down to the nearest interval (e.g. minute). I can do a pull request if it makes sense, but there may be a better way of doing this.
![gemworks_error](https://user-images.githubusercontent.com/1524593/151675615-a6be4d50-b094-4b48-9443-3b7989121ad5.png)

**Comment by ilmoi** [comment]
what you're running into are the limitations of u64 based math. It doesn't have enough precision.

what's happening is: when you refresh the farmer state before the minute is up, it rounds down to 0, and then like you set restarts the timer

the way around this is to use u128 / u192 or more - but that would add significant complexity to the program and I decided to skip for v0. 

the part about anyone refreshing farmers and how that can lead to 0 rewards is fascinating - thank you for pointing that out. Still the more reason to fix in v1!

**Comment by dshaw002** [comment]
So, I made an interested workaround that rounds the updated_ts to the nearest previous interval. I actually think this could be a solid workaround to using u182/u192 math if you added another state value for this rounded updated time. Let me know if it makes sense and I could work on making it a formal pull request. 

It only requires one small code change in farm.rs:

`fn update_accrued_reward_by_type(
        &mut self,
        now_ts: u64,
        farm_rarity_points_staked: u64,
        farmer_rarity_points_staked: Option<u64>,
        farmer_reward: Option<&mut FarmerReward>,
        reenroll: bool,
    ) -> ProgramResult {
        match self.reward_type {
            RewardType::Variable => self.variable_rate.update_accrued_reward(
                now_ts,
                &self.times,
                &mut self.funds,
                farm_rarity_points_staked,
                farmer_rarity_points_staked,
                farmer_reward,
            ),
            RewardType::Fixed => {
                // for fixed rewards we only update if Farmer has been passed
                if farmer_reward.is_none() {
                    return Ok(());
                }
                
                let freward = farmer_reward.unwrap();
                
                if freward.fixed_rate.promised_schedule.denominator > 1 {    
                    let end_schedule_ts = freward.fixed_rate.begin_schedule_ts.try_add(freward.fixed_rate.promised_duration);
                    let upper_bound = std::cmp::min(now_ts, end_schedule_ts?);
                    let updated_ts = upper_bound.try_sub(upper_bound.try_sub(freward.fixed_rate.begin_staking_ts)?.try_rem(freward.fixed_rate.promised_schedule.denominator)?);
                    msg!("Previous now_ts: {}", now_ts);
                    
                    // NEW CODE
                    self.fixed_rate.update_accrued_reward(
                        updated_ts?,
                        &mut self.times,
                        &mut self.funds,
                        farmer_rarity_points_staked.unwrap(),
                        //farmer_reward.unwrap(),
                        freward,
                        reenroll,
                    ) // END NEW
                } else {
                    // OLD CODE 
                    self.fixed_rate.update_accrued_reward(
                        now_ts,
                        &mut self.times,
                        &mut self.funds,
                        farmer_rarity_points_staked.unwrap(),
                        //farmer_reward.unwrap(),
                        freward,
                        reenroll,
                    ) // END OLD
                }
            }
        }
    }`

**Comment by dshaw002** [comment]
Closed with latest merge
