### ISSUE TITLE
Code not parseable

### ISSUE THREAD

**Issue by mustafa-can** [gemworks/gem-farm#20]
I ran "anchor build" command  and after this line:
  The program address will default to this keypair (override with --program-id):
    .../gem_bank-keypair.json
I get this error:
  thread 'main' panicked at 'Code not parseable: Error("bump targets should not be provided with init. Please use bump without a target.")', lang/syn/src/idl/file.rs:353:58
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Could anyone help ?

**Comment by mustafa-can** [comment]
so gem-farm-keypair.json is not generated.

**Comment by mustafa-can** [comment]
i solved the issue. thanks

**Comment by NathRyuzaki** [comment]
hey,
i have the same issue, how to fix this? thanks
