### ISSUE TITLE
Staking is not working

### ISSUE THREAD

**Issue by numisman** [gemworks/gem-farm#23]
Is the vanilla UI reporting accrued rewards in fractions of a token?

I set up the calculations in the farm to accrue 1200 tokens per NFT per second, and set the Denominator to 86400 (number of seconds in a day) so that the math would be good.  The accrued reward is reporting as "6", but when I try to claim, it shows that I received 0.0000006 of our token.

So...do I have to multiply by a factor of 100000 for it to work?

Here's the farm config (there are previous attempts here but the current setup is what I have).
![image](https://user-images.githubusercontent.com/87335441/154546422-9b823871-3192-44b0-ba11-cac4eee5b6d6.png)

![image](https://user-images.githubusercontent.com/87335441/154546334-bbb01dcc-bbfc-4aa2-b7ef-c1a5a86e82d0.png)

![image](https://user-images.githubusercontent.com/87335441/154546266-c95e2352-fa2b-40bc-86a2-a07874ace00e.png)

It appears that we're reporting in Lamports (if the currency was SOL) but we're using our own token.

Thanks in advance for the help!

**Comment by holywend** [comment]
I believe this is because your token is a fractional token? We also run into a similar problem. 

In our case, we put 1 base rate and denominator of 60, expecting 1 token per minute. But the user gets 0 tokens instead, when we observe it more, the user actually gets 0.000000001 token instead of 1. the solscan limitation made it shown as 0 instead.

Too bad we also have not found the work around this as of yet.

**Comment by numisman** [comment]
That's exactly it, @holywend. We had to multiply by a factor of the decimals to get the math to work right.  I don't quite get WHY this is an issue, but it is.  Was looking for an actual explanation that made sense.

Thanks for answering!  I appreciate the response.

**Comment by l8nit3tr0ubl3** [comment]
has this been resolved in the code? or do we still need to multiply by a factor of the decimals? I have 'mainnet' farm and want to be sure ive done my math correctly.......

**Comment by freaktree** [comment]
I have run into this issue as well today. Created farm on mainnet, the claim amount is correct  on interface but when you claim the transaction is less the decimal places..

**Comment by holywend** [comment]
@l8nit3tr0ubl3 and @freaktree yeah you will need to multiply by the decimal places
eg 4 decimal, then the rate will be x10000 and also when you fund x10000

**Comment by PrettyBoyHelios** [comment]
@holywend is there a way to achieve this without minting by that multiplier?
