### ISSUE TITLE
TS2339: Property 'findWhitelistProofPDA' does not exist on type 'GemBank'.

### ISSUE THREAD

**Issue by spacexastro** [gemworks/gem-farm#30]
After updating the sdk I get the following error:
![1FBFAB4C-C07F-470B-8CEB-239FE590600B_1_201_a](https://user-images.githubusercontent.com/89827884/155436939-78dcae32-61fd-4376-8058-8818b9200c84.jpeg)

**Comment by BungeeDesign** [comment]
Remove `this.` and make sure your importing `findWhitelistProofPDA `. 

Should look like this:

`import {
  findWhitelistProofPDA,
  GEM_BANK_PROG_ID,
  GemBankClient,
  WhitelistType,
} from '@gemworks/gem-farm-ts';`

**Comment by spacexastro** [comment]
bless bro
