### ISSUE TITLE
How can I get an array of the farmers and the gem mint addresses?

### ISSUE THREAD

**Issue by numisman** [gemworks/gem-farm#41]
I want to allow our community to stake as well as earn airdrops, but when you stake your NFT gets moved to a "gem box", and I don't want to mistakenly airdrop to the gem box account rather than the owner's wallet.  So I need to get the owner's wallet and use that with the gems stored in the gem boxes.

I've been all over the codebase and I believe that I can gain access to these objects by using the bank Id and querying the blockchain, but I do not see how this is possible by traversing through Solscan.io.  Also - I see that on the found farm object you can access the account - which shows farmerCount and gemsStaked variables.  But for the life of me I don't see how to get the underlying farmers and gems.  Also the Bank --> Vault --> Gem Box --> Gem Deposit Receipt relationships appear to allow me to get what I need, but I don't see HOW to grab them this way.  I would hope there would be a way to get to something like Bank.Vault.GemBox.GDR to be able to get all of the info I need, but I really don't see how this is possible because it does not appear that these get exposed, or I don't know how to pull them properly.

Is there anyone out there that can suggest a way to pull the list of stakers and their associated gems?

**Comment by numisman** [comment]
I think I have it.  In Manager.vue, I added a bit of code to findFarmsByManager to get all of the Gem Deposit Receipts.  By parsing this out, I should have the ability to backtrace the gem to the owner and then airdrops can happen with that.

Thanks again @ilmoi for the great repo with the hard stuff figured out!

**Comment by danvernon** [comment]
@numisman hey can you share what you did here?

**Comment by Josho39** [comment]
@numisman Please share how you did here
