### ISSUE TITLE
Fixed funding - how to reward EXACTLY 69 tokens per day?

### ISSUE THREAD

**Issue by numisman** [gemworks/gem-farm#63]
This SHOULD be straightforward but the math isn't working out for me - please help...

If I use a reward setup of Fixed with a base rate of 0.0007986111111  (69/86400 seconds / day) I can't, because it throws an error because it can't use decimal values for some reason.
So... I try using 7986111111 as the Base rate with the Denominator set to 100000 so that the math SHOULD work out.
The value it accrues in my wallet is off.
So... I try to approximate using 7986 for the Base rate and 10 for the denominator because it seems to work out closer to what it should be.
BUT HOW DO I SET IT UP TO BE ABLE TO PROVIDE EXACTLY 69 TOKENS PER DAY PER TOKEN?  What are the settings?
Thanks

**Comment by numisman** [comment]
So I just spent the last 6 hours massaging things.
Here's what it came down to:
![image](https://user-images.githubusercontent.com/87335441/159849292-a5823221-cca9-4234-963d-a0ac54731f07.png)
My question - WHY?!??!?!?!?!   How does 7986 with a denominator of 10 work out to 69/day?
I understand that 69 / (60 seconds * 60 minutes * 24 hours) = 0.0007986111111.
But WHY do I need the denominator?  Why can't I just put 69 Tokens /gem /day somewhere and have the math work under the covers?

**Comment by numisman** [comment]
bump.  Are there any ideas here?

**Comment by UPLukeet** [comment]
Use a denominator of 86400(seconds in a day) base rate of 69. This should give stakers 69 tokens once per day.

**Comment by numisman** [comment]
Thanks!  I'll give that a shot.

**Comment by Tynew240** [comment]
Don't know if you got it but what you need to do is 69000000000 for your per second pay with a denominator of 86,400

**Comment by numisman** [comment]
Yup - this did it and has the benefit of being fairly straightforward!  Thanks for the help.  Closing the ticket now.
