### ISSUE TITLE
Staking error - Not enough account keys given to the instruction

### ISSUE THREAD

**Issue by gsdeabr** [gemworks/gem-farm#81]
Hi, when I'm trying to stake/unstake I get the following error, it was working fine since then.

`Program log: AnchorError caused by account: fee_acc. Error Code: AccountNotEnoughKeys. Error Number: 3005. Error Message: Not enough account keys given to the instruction`
`consumed 19538 of 200000 compute units`
`failed: custom program error: 0xbbd`

Do you know a solution for that ?

**Comment by numisman** [comment]
Update the version of @gemfarm in your package.js.  He put out a tweet about this.  https://twitter.com/_ilmoi
