### ISSUE TITLE
Unintentional (presumably) overcharging for the staking tax

### ISSUE THREAD

**Issue by dylie-eth** [gemworks/gem-farm#82]
I understand that you want to get paid for all the effort you've put into creating this program and repository by implement taxes for staking and unstaking. 

That being said, flashDeposit transactions currently charge .00593 sol in tax, even though you state that it should cost .002 sol in tax. I'm not sure if this is an oversight or a misunderstanding on my part, but I figured I'd post this issue anyway.

Additionally, since you need to call unstake() twice in order to both end staking and end the cooldown (necessary to withdraw gems), wouldn't it end up charging .004 sol in tax? I'm assuming this "overcharge" is currently "paid" out of the remaining amt in the .00593 for flash depositing, but this still leaves an approximate .004 tax per stake/unstake...

**Comment by ilmoi** [comment]
thanks for posting

yeah so the flash deposit one is a weird one. You've seen the code. It charges 0.002. In the wallet I also only ever see +0.002 transctions, no +0.004 or +0.00593. I suspect the rest of the cost ("tax" as you call it) comes from the expensive "extraCompute" instruction that's used to execute flashDeposit.

But really I'm not sure. If you figure out where it comes from (and where it goes!) - let me know, maybe we can can find a way to reduce it.

0.002 is here to stay. 20c is not a crazy amount to charge per staking/unstaking (competitors charge closer to 0.01). I needed a way to grow with the projects the program is serving - that's a way of doing it.

**Comment by dylie-eth** [comment]
I know it shows .002 in the code, which is why I'm honestly confused. I noticed that it properly charged .002 for the first time an NFT has been flash deposited, then charges .00593 for any subsequent flash deposits.

I'll put some solscan links in here so you can see. It doesn't directly take the .00593 as a tax, but deposits the sol into accounts whose balance get drained after withdrawing. I'm assuming this occurs because when unstaking, you technically need to unstake twice, once to end the staking period, then a second time to end the cooldown. Then, you withdraw the gem, and have to reinitiate staking if you want to ensure they continue staking their other gems. The .002 tax from each of these stacks upon each other, which I think ends up resulting in a ~.006 tax to unstake?

FLASH DEPOSIT: https://solscan.io/tx/3yWkjmngbMY3NgF1GPUZL9nChw8qUwhXY9uHh7sfMwAVMKYKXdbxgfjSgqNJAELNtdDKhmcJ1FmbXwR4xkEyYptg

WITHDRAW: https://solscan.io/tx/3JUza47NcZCbkwczLPd75wVTPNxTQBegx7UXyiy7YxugihZ7ffMmVKcSJUqMY1YzUjqKPZjfg7CHSGLEx6cG2kQF

**Comment by ilmoi** [comment]
Re (1) - my suspicion is it's the extra compute ix. Without it it's not possible to do flash-deposits. The code:
```
  createExtraComputeIx(newComputeBudget: number): TransactionInstruction {
    const data = Buffer.from(
      Uint8Array.of(
        0,
        ...new BN(newComputeBudget).toArray('le', 4),
        ...new BN(0).toArray('le', 4)
      )
    );
```

As you can see on the first link there's only ever 1 transfer going to the fee account, and it's sized 0.002.

Re (2) - yeh currently it's 0.002 for both unstaking and cooldown. Don't think that's unreasonable - we're not talking about 2.5% that eg ME charges on NFT sales.

**Comment by ilmoi** [comment]
see latest PR. new fee structure:
- stake (total) 0.002
- unstake (total) 0.002
- flash deposit (since you're kinda staking but not really) 0.001 on top of any fees related to extra compute ix

**Comment by dylie-eth** [comment]
appreciate the quick response and understanding :) 

I'm not rlly sure bout the extraCompute being the reason it costs more, as even without it, it showed the same balance changes. 

🤷‍♂️
