### ISSUE TITLE
Start farm doesn't work. Custom program code: 0x1

### ISSUE THREAD

**Issue by fennyflop** [gemworks/gem-farm#86]
When I try to create a new farm
![image](https://user-images.githubusercontent.com/67952753/166441271-1c17036a-a980-45d3-a716-db7768359d5e.png)
I keep gettting this error:
![image](https://user-images.githubusercontent.com/67952753/166440874-ac890f81-408e-47e0-af31-884c41f93e27.png)

What I think causes the error (i may be wrong):
When I click on "Start Farm", i guess that i need to transfer some sol, but the only thing i see is the commission
![image](https://user-images.githubusercontent.com/67952753/166441668-3de2dea0-5d33-4e6e-9774-9c6950c2fbc1.png)

How can I bypass this? I think this error is my problem, yet I tried to do the same thing on my laptop and the problem is the same

**Comment by sourcandydev** [comment]
Error code 0x1 means InsufficientFunds. You need 2.5 SOL + gas fees to deploy a Farm. I see that you are on Devnet, so try to fund your wallet on https://solfaucet.com and try again.

**Comment by sourcandydev** [comment]
It's exactly what the last line of the error says - you need 2.5 SOL, but you have only 1.96 SOL

<img width="658" alt="image" src="https://user-images.githubusercontent.com/93947731/166445934-8418fc37-f54c-46bb-b19b-49858a12ccb6.png">

**Comment by fennyflop** [comment]
okay i guess i'm tripping ://// 
thanks bro 👍
